import { Cat } from './cat.type'

export const CATS: Cat[] = [
  {
    id: 1,
    name: 'Moustache',
    breed: 'Européen',
    colors: ['blanc', 'noir'],
    birthyear: 2024,
    birthplace: 'Paris',
  },
  {
    id: 2,
    name: 'Gribouille',
    breed: 'Siamois',
    colors: ['marron', 'crème'],
    birthyear: 2023,
    birthplace: 'Lyon',
  },
  {
    id: 3,
    name: 'Minou',
    breed: 'Maine Coon',
    colors: ['gris', 'blanc'],
    birthyear: 2022,
    birthplace: 'Marseille',
  },
  {
    id: 4,
    name: 'Bella',
    breed: 'Persan',
    colors: ['roux'],
    birthyear: 2021,
    birthplace: 'Toulouse',
  },
  {
    id: 5,
    name: 'Simba',
    breed: 'Bengal',
    colors: ['doré', 'noir'],
    birthyear: 2020,
    birthplace: 'Nice',
  },
  {
    id: 6,
    name: 'Choupette',
    breed: 'Chartreux',
    colors: ['noir'],
    birthyear: 2019,
    birthplace: 'Bordeaux',
  },
  {
    id: 7,
    name: 'Félix',
    breed: 'Abyssin',
    colors: ['fauve'],
    birthyear: 2024,
    birthplace: 'Nantes',
  },
  {
    id: 8,
    name: 'Luna',
    breed: 'Sphynx',
    colors: ['rose', 'gris'],
    birthyear: 2018,
    birthplace: 'Strasbourg',
  },
  {
    id: 9,
    name: 'Gizmo',
    breed: 'Ragdoll',
    colors: ['blanc', 'gris'],
    birthyear: 2023,
    birthplace: 'Lille',
  },
  {
    id: 10,
    name: 'Nala',
    breed: 'Scottish Fold',
    colors: ['crème', 'brun'],
    birthyear: 2022,
    birthplace: 'Rennes',
  },
  {
    id: 11,
    name: 'Tigrou',
    breed: 'Norvégien',
    colors: ['tigré', 'blanc'],
    birthyear: 2021,
    birthplace: 'Montpellier',
  },
]
